export const PAGEVIEW_GET_FILE = 'get-file'
export const PAGEVIEW_UPLOAD_FILE = 'upload-file'
export const PAGEVIEW_DOWNLOAD_FILE = 'download-file'
export const PAGEVIEW_SHARE_FILE = 'share-file'
export const PAGEVIEW_RENEW_FILE = 'renew-file'
export const PAGEVIEW_BILLING_RECORDS = 'billing-records'
export const PAGEVIEW_DELETE_FILE = 'delete-file'

export const EVENT_GET_FILES_DONE = 'get-files-done'
export const EVENT_GET_FILES_FAIL = 'get-files-fail'
export const EVENT_UPLOAD_DONE = 'upload-done'
export const EVENT_UPLOAD_FAIL = 'upload-fail'
export const EVENT_DOWNLOAD_DONE = 'download-done'
export const EVENT_DOWNLOAD_FAIL = 'download-fail'
export const EVENT_DELETE_DONE = 'delete-done'
export const EVENT_DELETE_FAIL = 'delete-fail'
export const EVENT_RENEW_DONE = 'renew-done'
export const EVENT_RENEW_FAIL = 'renew-fail'
