export const CONTRACT_LIST = 'ppio_sdk_contract_List'
export const GET_FILE_INFO = 'ppio_sdk_file_info'
export const CREATE_DOWNLOAD = 'ppio_sdk_create_download'
export const GET_DOWNLOAD_STATUS = 'ppio_sdk_download_status'
export const CANCEL_DOWNLOAD = 'ppio_sdk_cancel_download'
export const CREATE_UPLOAD = 'ppio_sdk_create_upload'
export const GET_UPLOAD_STATUS = 'ppio_sdk_upload_status'
export const CANCEL_UPLOAD = 'ppio_sdk_cancel_upload'
