export const CONTRACT_LIST = 'ppfs_contract_List'
export const GET_FILE_INFO = 'ppfs_file_info'
export const CREATE_DOWNLOAD = 'ppfs_create_download'
export const GET_DOWNLOAD_STATUS = 'ppfs_download_status'
export const CANCEL_DOWNLOAD = 'ppfs_cancel_download'
