export const MUT_SET_USER_DATA = 'mutation_setUserData'
export const MUT_LOGIN = 'mutation_login'
export const ACT_LOGIN = 'action_login'
export const MUT_LOGOUT = 'mutation_logout'
export const ACT_LOGOUT = 'action_login'
export const MUT_SET_JOURNAL = 'mutation_setUserJournal'
export const ACT_GET_JOURNAL = 'action_getUserJournal'
export const ACT_REFRESH_USER = 'action_refresh'

export const MUT_SET_FILE_LIST = 'mutation_setFileList'
export const ACT_SET_FILE_LIST = 'action_setFileList'
export const MUT_REMOVE_FILE = 'mutation_removeFile'
export const ACT_REMOVE_FILE = 'action_removeFile'
export const MUT_RENAME_FILE = 'mutation_renameFile'
export const ACT_RENAME_FILE = 'action_renameFile'
export const MUT_GET_FILE = 'mutation_getFile'
export const ACT_GET_FILE = 'action_getFile'

export const MUT_SECURE_FILE = 'mutation_secureFile'
export const ACT_SECURE_FILE = 'action_secureFile'
export const MUT_SHARE_FILE = 'mutation_shareFile'
export const ACT_SHARE_FILE = 'action_shareFile'

export const MUT_SET_TASK_DATA = 'mutation_setTaskData'
export const MUT_CREATE_TASK = 'mutation_createTask'
export const MUT_REMOVE_TASK = 'mutation_removeTask'

export const MUT_ADD_DL_TASK = 'mutation_addDownloadTask'
export const ACT_CREATE_DL_TASK = 'action_createDownloadTask'
export const MUT_RM_DL_TASK = 'mutation_removeDownloadTask'
export const ACT_CANCEL_DL_TASK = 'action_cancelDownloadTask'
export const MUT_SET_DL_STATUS = 'mutation_setDownloadStatus'
export const ACT_GET_DL_STATUS = 'action_getDownloadStatus'

export const MUT_ADD_UL_TASK = 'mutation_addUploadTask'
export const MUT_RM_UL_TASK = 'mutation_removeUploadTask'

export const TASK_TYPE_DOWNLOAD = 'taskType_download'
export const TASK_TYPE_UPLOAD = 'taskType_upload'
